fixtures:
  symlinks:
    hugo: "#{source_dir}"
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.14.0'
    remotefile:
      repo: 'https://github.com/lwf/puppet-remote_file.git'
      ref: 'v1.1.3'